{% set name = "r-xtensor" %}
{% set posix = 'm2-' if win else '' %}
{% set native = "m2w64-" %}
{% set version = "0.13.1" %}
{% set sha256 = "16d9b06617f41d11b32768556f7743e8138c9a078ea093b7ae75485b4cd2c471" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/Xtensor.R/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - xtensor-r >=0.13.0,<0.14.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - {{ pin_compatible('xtensor-r', max_pin='x.x') }}

test:
  commands:
    - $R -e "library('xtensor')"           # [not win]
    - "\"%R%\" -e \"library('xtensor')\""  # [win]

about:
  home: http://github.com/xtensor-stack/Xtensor.R
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R bindings for xtensor, the C++ tensor algebra library
  description: Multi dimensional arrays with broadcasting and lazy computing
  doc_url: https://xtensor-r.readthedocs.io/
  dev_url: https://github.com/xtensor-stack/Xtensor.R

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
